### ISSUE TITLE
Dark Soft UI error

### ISSUE THREAD

**Issue by a-lunatic** [KTibow/lovelace-dark-soft-ui-theme#10]
I get this error with the Dark Soft UI theme setting

Logger: homeassistant.helpers.template
Source: helpers/template.py:1378
First occurred: 15:56:13 (1 occurrences)
Last logged: 15:56:13

Template variable error: 'dict object' has no attribute 'entity' when rendering '@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(359deg); } } state-badge { {% if config.entity.startswith('fan.') and is_state(config.entity, 'on') %} animation: spin 4s infinite linear; {% endif %} }'

**Comment by a-lunatic** [comment]
Still an issue

**Comment by KTibow** [comment]
Sorry, I've been taking a break from GitHub notifications lately (I've probably subscribed to too many repos). So what badge / frontend config setup do you have? If you change `config.entity` to `config['entity']` in the theme's source, does it work?
