### ISSUE TITLE
Top edit header is missing when using theme

### ISSUE THREAD

**Issue by Clarky3** [KTibow/lovelace-dark-soft-ui-theme#11]
I can't exit the dashboard editor as the top edit header is missing when using theme. As you can see the X to exit is stuck in half at the top?

![image](https://user-images.githubusercontent.com/8182599/144115333-afcbb716-0d87-462d-9bc3-fa0401ad0bb2.png)

**Comment by KTibow** [comment]
here's a theme im using rn
```
Soft UI:
  card-mod-theme: Soft UI
  card-mod-card: |
    ha-card {
      margin: 20px;
      border-radius: 15px;
      background-color: var(--primary-background-color);
    }
  app-header-background-color: var(--primary-background-color)
  app-header-text-color: var(--primary-text-color)
  app-header-selection-bar-color: var(--primary-color)
  card-mod-root: |
    paper-tab[aria-selected="true"] {
      color: var(--primary-color);
    }
  accent-color: var(--primary-color)
  divider-color: transparent
  card-background-color: var(--primary-background-color)
  paper-item-icon-color: var(--secondary-text-color)
  primary-background-color: "#222222"
  modes:
    dark:
      primary-color: "#4C3FF9"
      light-primary-color: "#7A71FB"
      primary-background-color: "#222222"
      primary-text-color: "#F7F8F9"
      ha-card-box-shadow: "-5px -5px 15px #2c2c2c, 5px 5px 15px #191919"
      soft-ui-pressed: "inset -4px -4px 5px #2c2c2c, inset 4px 4px 5px #191919"
    light:
      primary-color: "#7A71FB"
      light-primary-color: "#918AFC"
      primary-background-color: "#F3F5F7"
      primary-text-color: "#222222"
      ha-card-box-shadow: "-5px -5px 15px #ffffff, 5px 5px 15px #ebebeb"
      soft-ui-pressed: "inset -4px -4px 5px #ffffff, inset 4px 4px 5px #ebebeb"
```

**Comment by Clarky3** [comment]
> here's a theme im using rn
> 
> ```
> Soft UI:
>   card-mod-theme: Soft UI
>   card-mod-card: |
>     ha-card {
>       margin: 20px;
>       border-radius: 15px;
>       background-color: var(--primary-background-color);
>     }
>   app-header-background-color: var(--primary-background-color)
>   app-header-text-color: var(--primary-text-color)
>   app-header-selection-bar-color: var(--primary-color)
>   card-mod-root: |
>     paper-tab[aria-selected="true"] {
>       color: var(--primary-color);
>     }
>   accent-color: var(--primary-color)
>   divider-color: transparent
>   card-background-color: var(--primary-background-color)
>   paper-item-icon-color: var(--secondary-text-color)
>   primary-background-color: "#222222"
>   modes:
>     dark:
>       primary-color: "#4C3FF9"
>       light-primary-color: "#7A71FB"
>       primary-background-color: "#222222"
>       primary-text-color: "#F7F8F9"
>       ha-card-box-shadow: "-5px -5px 15px #2c2c2c, 5px 5px 15px #191919"
>       soft-ui-pressed: "inset -4px -4px 5px #2c2c2c, inset 4px 4px 5px #191919"
>     light:
>       primary-color: "#7A71FB"
>       light-primary-color: "#918AFC"
>       primary-background-color: "#F3F5F7"
>       primary-text-color: "#222222"
>       ha-card-box-shadow: "-5px -5px 15px #ffffff, 5px 5px 15px #ebebeb"
>       soft-ui-pressed: "inset -4px -4px 5px #ffffff, inset 4px 4px 5px #ebebeb"
> ```

This resolves the issue completely, must be something wrong with the versions on HACS/Github?

**Comment by KTibow** [comment]
No the theme I posted is a completely new version.

**Comment by KTibow** [comment]
Should I bother making this repository host the new version?

**Comment by Clarky3** [comment]
> Should I bother making this repository host the new version?

if i'm honest, i prefer the theme on the main git, just that bug is the deal breaker

**Comment by KTibow** [comment]
If you remove the card-mod part for the header, does that fix it?
