### ISSUE TITLE
Theme select

### ISSUE THREAD

**Issue by micmouritzen** [KTibow/lovelace-dark-soft-ui-theme#13]
I have added all theme-names to my configuration.yaml file among all my other themes because i have a theme select on my dashboard. These themes are shown on the list, but does not appear when i select it. Is it possible to do this?

**Comment by KTibow** [comment]
1. What the heck do you mean by
> I have added all theme-names to my configuration.yam
2. This repo is outdated. Please use [lovelace-soft-theme](https://github.com/KTibow/lovelace-soft-theme) instead. It doesn't have different colors, but it's more maintained.
