### ISSUE TITLE
Badges with picture dont work

### ISSUE THREAD

**Issue by daranto** [KTibow/lovelace-dark-soft-ui-theme#3]
Hello,

apparently the theme does not work correctly when using badges with pictures. Could you check this? The pictrues are not in the badges after the change to your theme.

Screenshot: [https://i.ibb.co/JzmWgvW/Unbenannt.jpg](url)

Daranto

**Comment by KTibow** [comment]
That's odd. Right-click on the center and choose "Inspect element" and take a screenshot of the browser console.

**Comment by KTibow** [comment]
Never mind I found out the problem.

**Comment by KTibow** [comment]
Fixed, will be added in next release.

**Comment by daranto** [comment]
Thanks for fixing!
