### ISSUE TITLE
All Cards aligned to the left

### ISSUE THREAD

**Issue by j0hnnyknt** [KTibow/lovelace-dark-soft-ui-theme#7]
after installing the latest theme update on Home Assistant 0.117 all my cards are aligned to the left of the page

[https://imgur.com/XJsfJXD](url)

**Comment by KTibow** [comment]
Your link is broken. I'll investigate

**Comment by KTibow** [comment]
Silly me forgot to update the release.

**Comment by KTibow** [comment]
Well I don't get this. Are you sure about this?

**Comment by j0hnnyknt** [comment]
removed and re-installed the theme and now all is working fine. thank you
